### ISSUE TITLE
the result of builtwith.list() is only 250

### ISSUE THREAD

**Issue by ballonJourn** [zcaceres/builtwith-api#8]
hello master zcaceres ,

thank you for your builtwith so that i can receive similar sites rapidly.

i am come from china and now using your builtwith-api to collect some sites using stripe tech,  but when the code done there is only 250 sites in my stripe.json file.

my api-key is free api

how can i get more info about this tech?

**Comment by zcaceres** [comment]
Hi @ballonJourn .

You have a include an `offset` (based on the offset value in the previous response) to paginate through the results. Check out the [BuiltWith API docs](https://api.builtwith.com/lists-api)

Good luck!

**Comment by ballonJourn** [comment]
thanks @zcaceres !
i have found the way to get more lists through api by this link https://api.builtwith.com/lists11/api.xml?KEY=0f23f6f1-05d6-47fa-b727-4620768b7f86&TECH=Stripe&COUNTRY=CN.
after setting the number of list such as list3, i can receive the sites what i want to get!
sincerely delivery my praise to you and your builtwith-api , this api really should be known by more and more coders.
